name: Cypress tests
on: push
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/spec.cy.js
      - name: Upload artefatos de teste
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-testes
        path: TCC-Cypress/cypress/report/