name: Cypress tests
on: push
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        run: |
          cd TCC-Cypress
          npx cypress run
          npm run report:generate

      - name: Upload artefatos de teste
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-testes
          path: TCC-Cypress/cypress/report/