name: Cypress tests
on: push
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and run Cypress
        run: |
          npm i
          npx cypress run
          npm run report:generate
          
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: cypress/report
